import { Geist, Geist_Mono } from "next/font/google";
import MuiThemeProvider from "@/providers/MuiThemeProvider";
import "./globals.css";
import "@fontsource/inter/300.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/caveat/400.css"; // Regular
import "@fontsource/caveat/500.css"; // Medium
import "@fontsource/caveat/600.css"; // Semi-Bold
import "@fontsource/caveat/700.css"; // Bold

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MuiThemeProvider>{children}</MuiThemeProvider>
      </body>
    </html>
  );
}
